Support build wasm
kevmoo/peanut.dart pull request #177
Opened 2024-08-11 04:06 UTC by nploi

fixed: https://github.com/kevmoo/peanut.dart/issues/176

2024-08-11 04:47 UTC, kevmoo commented on lib/src/flutter.dart
> +    ] else ...[
```suggestion
    if (options.wasm) '--wasm',
    else ...[
```

Does this work?

2024-08-11 04:53 UTC, nploi commented on lib/src/flutter.dart
> +    ] else ...[
yes.

2024-08-12 09:32 UTC, nploi commented
hi @kevmoo, can you help to review again ?

2024-08-12 22:00 UTC, kevmoo commented on lib/src/flutter.dart
> +    ] else ...[
thanks!

2024-08-12 22:01 UTC, kevmoo requested changes

2024-08-12 22:01 UTC, kevmoo commented on CHANGELOG.md
> +
delete extra line

2024-08-12 22:01 UTC, kevmoo commented on CHANGELOG.md
> +## 5.0.2
```suggestion
## 5.1.0
```

It's a feature!

2024-08-12 22:01 UTC, kevmoo commented on pubspec.yaml
> +version: 5.0.2
```suggestion
version: 5.1.0
```

adding a feature!

2024-08-13 03:22 UTC, nploi commented
fixed your comments @kevmoo

2024-08-13 03:26 UTC, kevmoo approved these changes

2024-08-13 15:22 UTC, kevmoo commented
@nploi – you'll need to run the build again to update the version file and we'll be good!

2024-08-13 15:31 UTC, nploi commented
> @nploi – you'll need to run the build again to update the version file and we'll be good!

@kevmoo  done  🙏

2024-08-13 16:43 UTC, merged