Update peanut.dart
kevmoo/peanut.dart pull request #178
Opened 2024-08-22 05:40 UTC by westlinkin

run post build dart script after flutter build

2024-08-30 20:54 UTC, kevmoo commented
Please add a changelog entry! thanks!

2024-09-01 03:41 UTC, westlinkin commented
I created another PR for the `changelog`. Sorry for the inconvenience.

https://github.com/kevmoo/peanut.dart/pull/179

2024-09-01 17:31 UTC, kevmoo commented
You can add that change here. Just push the branch again

2024-10-09 18:44 UTC, kevmoo commented
you'll have to cleanup the changelog.

2024-10-22 01:25 UTC, kevmoo requested changes

2024-10-22 01:25 UTC, kevmoo commented on CHANGELOG.md
> +## 5.2.1
put this under the `5.2.0-wip` bit – since that release hasn't shipped yet!

2025-02-04 00:10 UTC, kevmoo commented
Closing this out. Please reopen if interested

2025-02-04 00:10 UTC, closed without merging